apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-pod-delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-pod-delete-cluster-role
rules:
  - apiGroups: ["extensions",""]
    resources: ["pods"]
    verbs: ["get","list","delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-pod-delete-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: falco-pod-delete
    namespace: default
roleRef:
  kind: ClusterRole
  name: falco-pod-delete-cluster-role
  apiGroup: rbac.authorization.k8s.io
